### ISSUE TITLE
Регистрация (юзер не залогинен)

### ISSUE THREAD

**Issue by Uta-Bin** [kevlampiev/carservices.web#86]
Регистрация. После ввода логина и пароля на экране не отображается, что юзер залогинился (не меняется картинка, не отображается, что вход выполнен)

**Comment by kevlampiev** [comment]
Непонятная ошибка. Как будто computed свойства не обновляются. Пробую разобраться

**Comment by kevlampiev** [comment]
На самом деле нужно явно указать пользователю, что нужно 8 симваолов в окне регистрации

**Comment by kevlampiev** [comment]
Сняли вопрос
